#!/usr/bin/env python3
import os, json, subprocess, hashlib, argparse, re
from pathlib import Path
ap=argparse.ArgumentParser(); ap.add_argument('--artifacts',type=Path,required=True); ap.add_argument('--profiles',default='wgpu-amd-vulkan,wgpu-nvidia-vulkan,wgpu-amd-gl,bgfx-amd-vulkan,bgfx-nvidia-vulkan,bgfx-amd-gl'); ap.add_argument('--extra',action='store_true');ap.add_argument('--alpha',action='store_true');ap.add_argument('--deep',action='store_true');ap.add_argument('--rtt-study',action='store_true');ap.add_argument('--viewport-study',action='store_true');ap.add_argument('--resources',action='store_true');ap.add_argument('--modes',default='native,nearest,fetch');ap.add_argument('--output-name',default='quality'); args=ap.parse_args()
out=args.artifacts/args.output_name;out.mkdir(exist_ok=True);runs=json.loads((out/'summary.json').read_text()) if (out/'summary.json').exists() else []
for profile in args.profiles.split(','):
    backend,gpu,api=profile.split('-'); env=dict(os.environ,DISPLAY=':0',XAUTHORITY='/home/dikluwe/.Xauthority',COIN_GLX_PIXMAP_DIRECT_RENDERING='1',COIN_GLXGLUE_NO_PBUFFERS='1',COIN_RENDER_REQUIRE_GL_REFERENCE='1',WGPU_BACKEND='gl' if api=='gl' else 'vulkan',COIN_BGFX_RENDERER='opengl' if api=='gl' else 'vulkan')
    env['VK_DRIVER_FILES']=env['VK_ICD_FILENAMES']='/usr/share/vulkan/icd.d/'+('nvidia_icd.json' if gpu=='nvidia' else 'radeon_icd.json')
    env['__GLX_VENDOR_LIBRARY_NAME']='nvidia' if gpu=='nvidia' else 'mesa';env['__EGL_VENDOR_LIBRARY_FILENAMES']='/usr/share/glvnd/egl_vendor.d/'+('10_nvidia.json' if gpu=='nvidia' else '50_mesa.json')
    if gpu=='nvidia':env['__NV_PRIME_RENDER_OFFLOAD']='1'
    else:env.pop('__NV_PRIME_RENDER_OFFLOAD',None)
    for mode in (list(dict.fromkeys(['native']+args.modes.split(','))) if args.extra else args.modes.split(',')):
        env['COIN_SAMPLING_STUDY']=mode
        for case,command in ([('viewport-study',['CoinRenderAdvancedTextureTest','--gpu','--sampling-viewport-study'])] if args.viewport_study else [('rtt-study',['CoinRenderAdvancedTextureTest','--gpu','--sampling-rtt-study'])] if args.rtt_study else ([('large-bindings',['CoinWgpuLargeBindingsTest']),('multi-device',['CoinWgpuMultiDeviceTest']),('stress',['CoinWgpuMultiDeviceTest','--stress'])] if backend=='wgpu' else [('instancing',['CoinBgfxInstancingTest'])]) if args.resources else [('deep',['CoinRenderAdvancedTextureTest','--gpu','--sampling-deep-study'])] if args.deep else [('alpha',['CoinRenderAdvancedTextureTest','--gpu'])] if args.alpha else ([('multitexture',['CoinRenderMultitextureTest']),('fragment-policy',['CoinRenderFragmentPolicyTest','--gpu'])] if args.extra else [('projective',['CoinRenderTextureSamplingTest','--projective-study']),('sampling',['CoinRenderTextureSamplingTest','--gpu']),('advanced',['CoinRenderAdvancedTextureTest','--gpu']),('procedural',['CoinRenderProceduralTextureTest','--gpu']),('rtt',['CoinRenderRttProfileTest','--mips-direct'])])):
            cmd=[str(args.artifacts/('build-'+backend)/'bin'/command[0]),*command[1:]];log=out/f'{profile}-{mode}-{case}.log'
            with log.open('w') as f:
                try:code=subprocess.run(cmd,env=env,stdout=f,stderr=subprocess.STDOUT,timeout=180).returncode
                except subprocess.TimeoutExpired:code=124
            content=log.read_text(errors='replace');runs.append(dict(profile=profile,mode=mode,case=case,command=cmd,exit=code,log=log.name,environment={k:v for k,v in env.items() if k in ['COIN_SAMPLING_STUDY','WGPU_BACKEND','COIN_BGFX_RENDERER','VK_DRIVER_FILES','__GLX_VENDOR_LIBRARY_NAME','__EGL_VENDOR_LIBRARY_FILENAMES','__NV_PRIME_RENDER_OFFLOAD','DISPLAY','XAUTHORITY','COIN_GLX_PIXMAP_DIRECT_RENDERING','COIN_GLXGLUE_NO_PBUFFERS']},binary_sha256=hashlib.sha256(Path(cmd[0]).read_bytes()).hexdigest(),log_sha256=hashlib.sha256(log.read_bytes()).hexdigest(),adapter=next((x for x in content.splitlines() if x.startswith('adapter=')),None),metrics=[x for x in content.splitlines() if 'samples=' in x]))
            (out/'summary.json').write_text(json.dumps(runs,indent=2));print(profile,mode,case,code,flush=True)
