#include <windows.h>
#include <Inventor/SoDB.h>
#include <Inventor/actions/CoinRenderAction.h>
#include <Inventor/rendering/CoinRenderTarget.h>
#include <Inventor/rendering/CoinRenderCapabilities.h>
#include <Inventor/rendering/CoinRenderNativeSurface.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoLightModel.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoCube.h>
#include <iostream>
#include <fstream>
#include <memory>
#include <vector>
#include <string>
static void ppm(const std::string&p,const std::vector<unsigned char>&v){if(v.size()!=64*64*4)return;std::ofstream f(p,std::ios::binary);f<<"P6\n64 64\n255\n";for(size_t i=0;i<v.size();i+=4)f.write((char*)&v[i],3);}
int main(int argc,char**argv){std::cout<<std::unitbuf;if(argc!=4)return 2;std::string policy=argv[1],mode=argv[2],prefix=argv[3];bool window=mode=="window";if((policy!="native"&&policy!="portable")||(mode!="window"&&mode!="offscreen"))return 2;SoDB::init();for(const char* dll : {"Coin4.dll","CoinRender4.dll"}) { char modulePath[MAX_PATH]{}; HMODULE module=GetModuleHandleA(dll); if(!module || !GetModuleFileNameA(module,modulePath,MAX_PATH)) return 2; std::cout << "loaded_module name=" << dll << " path=" << modulePath << std::endl; }CoinRenderAction::initClass();CoinRenderCapabilities caps{};if(coin_render_query_capabilities_for_renderer(window?COIN_RENDER_EXPERIMENTAL_WIN32_WINDOW:COIN_RENDER_EXPERIMENTAL_OFFSCREEN,COIN_RENDER_RENDERER_D3D12,&caps,sizeof(caps))||caps.renderer!=4||caps.vendor_id!=0x10de)return 77;std::cout<<"receipt renderer="<<caps.renderer<<" vendor="<<std::hex<<caps.vendor_id<<" device="<<caps.device_id<<std::dec<<" adapter="<<caps.adapter_name<<" mode="<<mode<<" policy="<<policy<<'\n';
HWND hwnd=nullptr;if(window){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"CoinRemovalCampaign";RegisterClassW(&c);hwnd=CreateWindowW(c.lpszClassName,L"Coin scoped native device removal",WS_POPUP,30,30,64,64,nullptr,nullptr,c.hInstance,nullptr);ShowWindow(hwnd,SW_SHOWNOACTIVATE);}
CoinRenderOptions o;o.renderer=COIN_RENDER_RENDERER_D3D12;o.textureSamplingPolicy=policy=="portable"?COIN_RENDER_SAMPLING_PORTABLE:COIN_RENDER_SAMPLING_NATIVE;auto create=[&](){if(!window)return CoinRenderTarget::createOffscreen(SbVec2i32(64,64),o);CoinRenderNativeSurfaceDescriptor d{};d.abiVersion=COIN_RENDER_NATIVE_SURFACE_ABI_VERSION;d.structSize=sizeof(d);d.type=COIN_RENDER_SURFACE_WIN32;d.native.win32.hinstance=GetModuleHandleW(nullptr);d.native.win32.hwnd=hwnd;return CoinRenderTarget::createWindow(d,SbVec2i32(64,64),o);};
auto*r=new SoSeparator;r->ref();auto*c=new SoOrthographicCamera;c->height=3;c->position=SbVec3f(0,0,5);r->addChild(c);auto*l=new SoLightModel;l->model=SoLightModel::BASE_COLOR;r->addChild(l);auto*m=new SoMaterial;m->diffuseColor=SbColor(.2f,.6f,.4f);r->addChild(m);r->addChild(new SoCube);
std::unique_ptr<CoinRenderTarget>t(create()),peer(CoinRenderTarget::createOffscreen(SbVec2i32(64,64),o));CoinRenderAction a(SbViewportRegion(64,64)),b(SbViewportRegion(64,64));a.setRenderTarget(t.get());b.setRenderTarget(peer.get());if(window)t->requestWindowReadbackRGBA();a.apply(r);b.apply(r);std::vector<unsigned char>before,peerBefore;t->readbackRGBA(before);peer->readbackRGBA(peerBefore);bool ok=a.getLastStatus()==CoinRenderAction::SUCCESS&&b.getLastStatus()==CoinRenderAction::SUCCESS&&before.size()==64*64*4;auto serial=t->getLastSubmissionSerial(),peerSerial=peer->getLastSubmissionSerial();ppm(prefix+"-before.ppm",before);
_putenv_s("COIN_BGFX_TEST_REMOVE_NATIVE_DEVICE_ONCE","1");m->diffuseColor=SbColor(.9f,.1f,.2f);a.apply(r);std::cout<<"lost status="<<a.getLastStatus()<<" serial_before="<<serial<<" serial_after="<<t->getLastSubmissionSerial()<<" diagnostic="<<a.getLastError().getString()<<'\n';ok=ok&&a.getLastStatus()==CoinRenderAction::DEVICE_LOST&&serial==t->getLastSubmissionSerial();const bool peerLost=peer->getStatus()==CoinRenderTarget::TARGET_LOST && peerSerial==peer->getLastSubmissionSerial();ok=ok&&peerLost;
std::cout<<"peer_lost_before_resubmit="<<peerLost<<" peer_serial_unchanged="<<(peerSerial==peer->getLastSubmissionSerial())<<'\n';
std::vector<unsigned char>after;t->readbackRGBA(after);ok=ok&&(after.empty()||after==before);std::cout<<"lost_no_publication="<<ok<<" peer_lost="<<peerLost<<" cached_pixels_retained="<<(after==before)<<" unavailable_pixels="<<after.empty()<<'\n';b.apply(r);std::vector<unsigned char>peerAuto;peer->readbackRGBA(peerAuto);bool peerRec=b.getLastStatus()==CoinRenderAction::SUCCESS && peerAuto.size()==64*64*4;
if(peerRec){const int expected[3]={230,26,51};for(int channel=0;channel<3;++channel)peerRec=peerRec&&std::abs(int(peerAuto[(32*64+32)*4+channel])-expected[channel])<=1;}
std::cout<<"peer_auto_status="<<b.getLastStatus()<<" diagnostic="<<b.getLastError().getString()<<" size="<<peerAuto.size();if(peerAuto.size()==64*64*4)std::cout<<" center="<<int(peerAuto[(32*64+32)*4])<<","<<int(peerAuto[(32*64+32)*4+1])<<","<<int(peerAuto[(32*64+32)*4+2]);std::cout<<'\n';ok=ok&&peerRec;ppm(prefix+"-peer-auto-recovered.ppm",peerAuto);std::cout<<"peer_auto_recovery="<<peerRec<<" explicit_new_submission=1\n";
a.setRenderTarget(nullptr);b.setRenderTarget(nullptr);t.reset();peer.reset();
m->diffuseColor=SbColor(.2f,.6f,.4f);t.reset(create());a.setRenderTarget(t.get());if(window)t->requestWindowReadbackRGBA();a.apply(r);std::vector<unsigned char>recovered;t->readbackRGBA(recovered);ok=ok&&a.getLastStatus()==CoinRenderAction::SUCCESS&&recovered==before&&t->getLastSubmissionSerial()>0;ppm(prefix+"-recovered.ppm",recovered);std::cout<<"recovery_status="<<a.getLastStatus()<<" target_status="<<t->getStatus()<<" diagnostic="<<a.getLastError().getString()<<'\n';std::cout<<"native_runtime_removal recovered="<<(a.getLastStatus()==CoinRenderAction::SUCCESS)<<" pixels_exact="<<(recovered==before)<<" result="<<ok<<" adapter_reset=0 driver_tdr=0\n";a.setRenderTarget(nullptr);t.reset();r->unref();if(hwnd)DestroyWindow(hwnd);return ok?0:1;}
