#ifndef COIN_RENDER_LEGACY_SOWGPUSCENEMANAGER_H
#define COIN_RENDER_LEGACY_SOWGPUSCENEMANAGER_H

// Source compatibility only. Rebuild clients against CoinRender.
#include <Inventor/rendering/CoinRenderSceneManager.h>
#define COIN_WGPU_DLL_API COIN_RENDER_DLL_API
typedef CoinRenderNativeSurfaceDescriptor SoWgpuNativeSurfaceDescriptor;
typedef CoinRenderReadbackTicket SoWgpuReadbackTicket;
typedef CoinRenderAction SoWgpuRenderAction;
typedef CoinRenderTarget SoWgpuRenderTarget;
typedef CoinRenderSceneManager SoWgpuSceneManager;

#endif // COIN_RENDER_LEGACY_SOWGPUSCENEMANAGER_H
