#ifndef COIN_RENDER_LEGACY_SOWGPUNATIVESURFACE_H
#define COIN_RENDER_LEGACY_SOWGPUNATIVESURFACE_H

// Source compatibility only. Rebuild clients against CoinRender.
#include <Inventor/rendering/CoinRenderNativeSurface.h>
#define COIN_WGPU_NATIVE_SURFACE_ABI_VERSION COIN_RENDER_NATIVE_SURFACE_ABI_VERSION
#define COIN_WGPU_SURFACE_APPKIT_LAYER COIN_RENDER_SURFACE_APPKIT_LAYER
#define COIN_WGPU_SURFACE_WAYLAND COIN_RENDER_SURFACE_WAYLAND
#define COIN_WGPU_SURFACE_WIN32 COIN_RENDER_SURFACE_WIN32
#define COIN_WGPU_SURFACE_XLIB COIN_RENDER_SURFACE_XLIB
typedef CoinRenderNativeSurfaceDescriptor SoWgpuNativeSurfaceDescriptor;
typedef CoinRenderNativeSurfaceType SoWgpuNativeSurfaceType;
typedef CoinRenderTarget SoWgpuRenderTarget;

#endif // COIN_RENDER_LEGACY_SOWGPUNATIVESURFACE_H
