import pathlib,difflib,subprocess,json,os,time,shutil
r=pathlib.Path(r'H:\Git\coin\build\sampling-win-20261010');src=r/'bgfx-device-loss-source/bgfx/src';h=src/'renderer_d3d12.h';s=h.read_text().replace(': m_traceResults(false)',': m_traceResults(false)\n\t\t\t, m_traceFile(NULL)').replace('bool m_traceResults;','bool m_traceResults;\n\t\tvoid* m_traceFile;');h.write_text(s,newline='\n')
p=src/'renderer_d3d12.cpp';s=p.read_text();s=s.replace('m_traceResults = NULL != std::getenv("COIN_BGFX_TRACE_D3D12_QUERY_RESULTS");','const char* traceFilename = std::getenv("COIN_BGFX_D3D12_QUERY_LOG");\n\t\tm_traceFile = NULL != traceFilename ? std::fopen(traceFilename, "ab") : NULL;\n\t\tm_traceResults = NULL != m_traceFile;');marker='void TimerQueryD3D12::shutdown()\n\t{';assert s.count(marker)==1;s=s.replace(marker,marker+'\n\t\tif (NULL != m_traceFile) std::fclose(static_cast<std::FILE*>(m_traceFile));\n\t\tm_traceFile = NULL;\n\t\tm_traceResults = false;');s=s.replace('std::fprintf(stderr, "COIN_BGFX_D3D12_QUERY','std::fprintf(static_cast<std::FILE*>(m_traceFile), "COIN_BGFX_D3D12_QUERY');p.write_text(s,newline='\n')
orig=pathlib.Path(r'H:\Git\coin\build\bgfx-windows-source\bgfx\src');(r/'bgfx-device-loss.patch').write_text(''.join(''.join(difflib.unified_diff((orig/n).read_text().splitlines(True),(src/n).read_text().splitlines(True),fromfile='a/bgfx/src/'+n,tofile='b/bgfx/src/'+n)) for n in ['renderer_d3d12.cpp','renderer_d3d12.h']))
e={k.upper():v for k,v in os.environ.items()};e['MSBUILDDISABLENODEREUSE']='1';rows=[]
for name,cmd in [('build',['cmake','--build',str(r/'bgfx-device-loss-build'),'--config','Release','--parallel','2']),('install',['cmake','--install',str(r/'bgfx-device-loss-build'),'--config','Release'])]:
 with (r/('bgfx-device-loss-query-file-'+name+'.log')).open('w') as f:code=subprocess.run(cmd,env=e,stdout=f,stderr=subprocess.STDOUT).returncode
 rows.append(dict(command=cmd,exit=code));(r/'bgfx-device-loss-query-file-ledger.json').write_text(json.dumps(rows,indent=2));print(name,code,flush=True)
 if code:raise SystemExit(code)
